### PR TITLE
OSD-12884 deploy a clusterurlmonitor for each hostedcontrolplane

### PR DESCRIPTION
**Pull request by yithian**
### What type of PR is this?
feature

### What this PR does / why we need it?
This PR adds clusterurlmonitors for hostedcontrolplanes so that SRE can monitor API availability of hosted clusters

### Which Jira/Github issue(s) this PR fixes?
Fixes [OSD-12884](https://issues.redhat.com//browse/OSD-12884)

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [x] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Comment by dustman9000** [comment]
Is there a reason you did not go through the generated policy path? You will just need to add the proper policy-generator-config.yaml where the original ClusterURLMonitor exists

**Comment by yithian** [comment]
> Is there a reason you did not go through the generated policy path? You will just need to add the proper policy-generator-config.yaml where the original ClusterURLMonitor exists

Mostly because I didn't know about it's existence or how to use it :)

Now that I'm trying it out though, it looks like it generates policies to configure the hosted clusters? However this PR is to monitor hosted clusters' api and so needs to target the management clusters (where the API runs). Is there a way to use the generated policy path to create policies that target the management clusters?

**Comment by yithian** [comment]
Closing this in favor of #1505

**Pull request closed without merging**
