### PR TITLE
OSD-10920 Proxy-enable token-refresher

### PR DESCRIPTION
**Pull request by mrbarge**
### What type of PR is this?
Feature

### What this PR does / why we need it?
- Creates a `token-refresher` ServiceAccount which the `token-refresher` Deployment now runs as.
- Adds an init container to the token-refresher `Deployment` which checks if the cluster has a cluster-wide proxy enabled, and if so, populates a new `token-refresher-proxy` `Secret` with the related values. Those values are then mounted from the `Secret` into the `token-refresher` pod as environment variables (`HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY`).
- Adds RBAC for the `token-refresher` ServiceAccount to be able to do the above task.

If the cluster has no proxy enabled, the `Secret` is still created and mounted, but the proxy values will be empty.

This is a desirable change because it is a common occurrence for clusters using a cluster-wide-proxy to end up with a crashlooping `token-refresher` as it cannot successfully contact `sso.redhat.com`. We do have a [documented requirement](https://docs.openshift.com/rosa/networking/configuring-cluster-wide-proxy.html#cluster-wide-proxy-network-prereqs_cluster-wide-proxy-configuration) to exclude `sso.redhat.com` from proxy traffic, but this would eliminate the need for that requirement.

### Which Jira/Github issue(s) this PR fixes?
[OSD-10920](https://issues.redhat.com//browse/OSD-10920)

### Special notes for your reviewer:
This was previously attempted in #1123 but that PR was rightly rejected because a `CronJob` is not the way to solve this. Hopefully this is more amenable.

### Pre-checks (if applicable):
- [X] Tested latest changes against a cluster (proxy-enabled and non-proxy-enabled)

### CODE REVIEW

**Comment by jharrington22** [comment]
@mrbarge nice, however the pod wont react to changes in the clusters proxy configuration correct?

**Review by jharrington22 — COMMENTED** [review]
@mrbarge nice, however the pod wont react to changes in the clusters proxy configuration correct?

**Comment by mrbarge** [comment]
@jharrington22 that's correct. However, a change of proxy configuration also results in a rolling reboot of all nodes, so, the pod should eventually restart as a result of that process and end up with the right configuration.

**Pull request merged**
