### PR TITLE
Use correct link to EFS CSI ops-sop doc

### PR DESCRIPTION
**Pull request by 2uasimojo**
The doc was ported to .md

### CODE REVIEW

**Comment by 2uasimojo** [comment]
This or PR #333

**Comment by 2uasimojo** [comment]
/hold

So the question here is whether it's okay for this doc (which is public?) to contain a link into a private repository.

If the intended audience of this doc is SREs anyway, then the benefit of having an arrow back to the master SOP that makes this work might outweigh the inconvenience/confusion of a 403 in the rare case that someone else tries to hit it.

**Comment by cblecker** [comment]
The SOP can link here.. we don't necessarily need a link the other way IMO

**Comment by 2uasimojo** [comment]
Okay, thanks for the input @cblecker. Closing.

**Pull request closed without merging**
