### PR TITLE
Velero alert on 3 failed backups

### PR DESCRIPTION
**Pull request by dofinn**
We currently have no SLO for storing 100% of hourly backups. This alert
appears too frequently to be paged on. Dropping this to 3 sequential
failed backups before alerting.

Evidence is available in pager duty.

### CODE REVIEW

**Comment by dofinn** [comment]
cc @jewzaam @RiRa12621 @cblecker

**Comment by mrbarge** [comment]
+1 from me - been seeing this somewhat regularly and almost always seems to have sorted itself out in subsequent jobs. This would be in keeping with similar "only alert if continuous jobs fail" work being done in cards like OSD-4540 and OSD-5354.

**Comment by cblecker** [comment]
/hold
for discussion

**Comment by RiRa12621** [comment]
Probably should be renaming the alert as well to not be misleading, since it's now not just one hourly backup that's being missed.
+1 to the idea

**Comment by jewzaam** [comment]
/lgtm

Seems like generally accepted.  I'll leave the hold in case we want to rename the alert.  I think it's fine the way it is given it is an hourly backup that was missed, but maybe it could be `Velero3ConsecutiveHourlyBackupsMissed`?

**Comment by cblecker** [comment]
Can we modify the "message" that is passed on L28?

Otherwise, yeah, I think this is probably the best for now, although suboptimal

**Comment by RiRa12621** [comment]
Should probably still have a Jira card to fix the underlying root cause in addition @cblecker

**Comment by dofinn** [comment]
> Can we modify the "message" that is passed on L28?
> 
> Otherwise, yeah, I think this is probably the best for now, although suboptimal

resolved in https://github.com/openshift/managed-cluster-config/pull/499/commits/32096cc5f4721b3604b27445806d3c834036b1ca +  alertName

**Pull request merged**
