### PR TITLE
Remove efs-csi

### PR DESCRIPTION
**Pull request by 2uasimojo**
The efs-csi SSS is superseded by the [AWS EFS Operator](https://github.com/openshift/aws-efs-operator), available on OperatorHub. See [this article](https://access.redhat.com/articles/5025181) for details.

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm
/approve
/hold

When you are ready for this to merge, please `/hold cancel`

**Comment by 2uasimojo** [comment]
cf. https://github.com/openshift/ops-sop/pull/821

**Comment by 2uasimojo** [comment]
Is there a thing I need to do to make this go in prod?

**Pull request merged**
