### PR TITLE
Remove unsupported logging resources

### PR DESCRIPTION
**Pull request by cblecker**
### What type of PR is this?
cleanup

### What this PR does / why we need it?
Removes all unsupported logging resources from MCC

### Which Jira/Github issue(s) this PR fixes?

_Fixes #_

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by cblecker** [comment]
@anik120 This might be the more complete version of what you were trying to do in #1150

**Comment by anik120** [comment]
Thank you for opening the PR! 🎉 I've closed my PR, and this PR lgtm, but I'm going to defer to folks who's more familiar than me with this repo to add the required label.

**Pull request merged**
