### PR TITLE
Multiwindowburn

### PR DESCRIPTION
**Pull request by RiRa12621**
Templated out multiwindow multiburn recording and alerting
from here on any other route just needs to add 

```
      record: route:error_slo:percent
      labels:
        route: console
      expr: 0.5
```
with their corresponding expr according to the SLO to get burn alerts

### CODE REVIEW

**Comment by RiRa12621** [comment]
/hold
needs metrics only available starting from 4.5 to work
cc @jeremyeder

**Comment by RiRa12621** [comment]
in the face of our upstream efforts: to get this upstream, we'd need the commitment frmo the console team or later on any other team for a component, which is added, that they will make this SLO

**Comment by brancz** [comment]
very nice :+1:

**Comment by metalmatze** [comment]
With the slo-libsonnet project I started using the `burnrate5m` suffix. I think that's a bit more readable.

`route:haproxy_route_backend_http_errors:ratio_rate1h`
to
`route:haproxy_route_backend_http_errors:burnrate1h`.

Otherwise, this is pretty much similar. :+1:

**Pull request closed without merging**
