### PR TITLE
added destination: "generated_deploy/acm-policies" in policy field in config.yaml

### PR DESCRIPTION
**Pull request by lnguyen1401**
### What type of PR is this?
feature
_(bug/feature/cleanup/documentation)_

### What this PR does / why we need it?
added destination in config.yaml so the new MCC refactor script can generate a policy based on config.yaml and remove the lists we're keeping in https://github.com/openshift/managed-cluster-config/blob/master/scripts/generate-policy-config.py , https://github.com/openshift/managed-cluster-config/blob/master/scripts/generate-subjectpermissions-policy-config.py

### Which Jira/Github issue(s) this PR fixes?
https://issues.redhat.com/browse/OSD-16052
_Fixes #_

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Comment by bdematte** [comment]
To properly work, I think we need all the generated resources under the same path (to be able to add all content to the template for hive) so the path value should rather be `acm-policies` than `generated_deploy/acm-policies`. If not, we will likely generate resources which aren't deployed.

In addition, we need to ensure we create a card for the policy which aren't managed through the script right now to ensure they are moved to new script as a follow-up step (and we add the policy destination at that time).

**Comment by lnguyen1401** [comment]
That makes sense. I have updated the destination path, and open a card for the resources not managed by script

**Comment by lnguyen1401** [comment]
cc @dustman9000

**Comment by jewzaam** [comment]
/hold

Want to understand downstream PR https://github.com/openshift/managed-cluster-config/pull/1689 before we accept this change.

**Review by rafael-azevedo — APPROVED** [review]
/lgtm

**Review by fahlmant — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
