### PR TITLE
Quick fix for disappearing SA on OSD

### PR DESCRIPTION
**Pull request by jewzaam**
https://issues.redhat.com/browse/OSD-6059

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm
/hold

Are we ready for this to be deployed?

**Comment by RiRa12621** [comment]
Can we wait til Monday @cblecker @jewzaam ?
I'd like to see if the e2e test I added, catches the original
Problem and then how it behaves after this is live

**Comment by jewzaam** [comment]
Good to have it land in stage, removing hold.  Don't expect to promote until next week anyway.

/hold cancel

**Comment by RiRa12621** [comment]
Well I guess, we couldn't wait 🤷‍♂️

**Comment by cblecker** [comment]
@RiRa12621 the tests should run on prod too, if you want to see the difference

**Pull request merged**
