### PR TITLE
OSD-6583 update token refresher image

### PR DESCRIPTION
**Pull request by dofinn**
Update version to https://quay.io/repository/observatorium/token-refresher?tag=master-2021-02-24-1e01b9c&tab=tags

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm
/hold

@dofinn @arjunrn Please monitor this roll out in stage to ensure it's successful. When one of you are ready for this to merge, feel free to `/hold cancel`

**Comment by dofinn** [comment]
@cblecker this is just a version bump. Currently the remoteWrite is already disabled as per https://github.com/openshift/managed-cluster-config/pull/720/files

We will look to renable in staging only with the new token refresher

**Comment by jharrington22** [comment]
:+1:

**Pull request merged**
