### PR TITLE
Update OSD branding for 4.4 changes

### PR DESCRIPTION
**Pull request by jewzaam**
https://issues.redhat.com/browse/OSD-3122

Works on 4.3.18
Works on 4.3.18 upgraded to 4.4.3, applied after upgrading

### CODE REVIEW

**Comment by jewzaam** [comment]
Putting a hold on it so we can have more eyes review the change before it's merged.  If it's accidentally promoted to prod it's very visible.

**Comment by cblecker** [comment]
/lgtm

I'm fine with merging this to stage whenever you're ready, @jewzaam.

I was able to check out this branch, and test it on my test cluster with the following:
```
oc replace -f deploy/osd-oauth-templates-errors/osd-oauth-templates-errors.secret.yaml -f deploy/osd-oauth-templates-login/osd-oauth-templates-login.secret.yaml -f deploy/osd-oauth-templates-providers/osd-oauth-templates-providers.secret.yaml
```

**Comment by jewzaam** [comment]
@cblecker updated

**Comment by jewzaam** [comment]
/hold cancel
got +1 in jira, ready for final review

**Pull request merged**
