### PR TITLE
OSD-7065: Pull token-refresher by digest

### PR DESCRIPTION
**Pull request by 2uasimojo**
[OSD-7065](https://issues.redhat.com/browse/OSD-7065)

### CODE REVIEW

**Comment by 2uasimojo** [comment]
/hold

We need to figure out who controls the [repository](https://quay.io/repository/observatorium/token-refresher?tag=master-2021-02-24-1e01b9c&tab=tags) for this so we can do whatever is necessary to avoid the "disappearing digest" problem.

**Comment by jharrington22** [comment]
@2uasimojo the digest going missing here would cause the token refresher pod CrashLoopBackoff alert on all OSD prod systems until we update this digest. I think we can move forward with it as long as we document the fix.

Not doing this means we don't get OSD metrics to MST which I guess is not critical but given we know how to fix errors I'd prefer to make this change.

**Comment by 2uasimojo** [comment]
> @2uasimojo the digest going missing here would cause the token refresher pod CrashLoopBackoff alert on all OSD prod systems until we update this digest. I think we can move forward with it as long as we document the fix.
> 
> Not doing this means we don't get OSD metrics to MST which I guess is not critical but given we know how to fix errors I'd prefer to make this change.

Ack. Give me a little bit to work with the observatorium team and see how hard it would be to implement "don't rebuild". If it's too hard, I'll document as you say and we'll move on.

**Comment by 2uasimojo** [comment]
> work with the observatorium team and see how hard it would be to implement "don't rebuild"

The team is receptive. I've proposed https://github.com/observatorium/token-refresher/pull/6.

**Comment by 2uasimojo** [comment]
https://github.com/observatorium/token-refresher/pull/6 just merged. We should update the sha we're using; then this should be ready to go.

**Comment by 2uasimojo** [comment]
> We should update the sha

Done

/hold cancel

**Comment by cblecker** [comment]
/lgtm
/approve

Thanks for updating this @2uasimojo !

**Pull request merged**
