### PR TITLE
chore: containerize the generation of files

### PR DESCRIPTION
**Pull request by boranx**
Fixes: https://issues.redhat.com/browse/OSD-6775

### CODE REVIEW

**Comment by 2uasimojo** [comment]
This change looks sane to me. Not sure why `$(CONTAINER_ENGINE)` isn't resolving, and I can't seem to log into the CI environment to fiddle around. Maybe the env has already expired? (Though that seems awful quick.)

/retest

**Comment by boranx** [comment]
Maybe the CI doesn't have a `CONTAINER_ENGINE` though it runs on my local

**Comment by 2uasimojo** [comment]
> Maybe the CI doesn't have a `CONTAINER_ENGINE` though it runs on my local

Ohhh, I understand now -- the CI env is already running in a container. You can't run docker from within a container.

This means we'll have to resort to some kind of trickery so the `make` targets know whether they're running in a container or not.

**Comment by 2uasimojo** [comment]
> This means we'll have to resort to some kind of trickery so the `make` targets know whether they're running in a container or not.

It would probably be adequate to simply detect whether `$(CONTAINER_ENGINE)` is set. Something like:

```make
ifeq ($(CONTAINER_ENGINE),)
	# We're already in a container
	oc ...
else
	# Running locally
	$(CONTAINER_ENGINE) run ...
endif
```

**Comment by boranx** [comment]
@2uasimojo agreed, the fix has just been applied which I think seems more cleaner now

**Comment by boranx** [comment]
@2uasimojo agreed, the fix has just been applied which I think seems more cleaner now

**Comment by 2uasimojo** [comment]
Tested this locally and via a [dummy commit](https://github.com/openshift/managed-cluster-config/pull/776). I wasn't expecting the hook to automatically run `make` and commit the changes -- when did that get added? -- but as far as this PR goes, everything works beautifully. Thanks @boranx !

/lgtm

**Comment by 2uasimojo** [comment]
> when did that get added?

According to git history, it has been there forever. Why did I always have to do this manually?

**Comment by boranx** [comment]
yeah, that's a nice bot trick :))

**Pull request merged**
