### PR TITLE
Reformat the hypershift policy names to be compatible with Cluster Service

### PR DESCRIPTION
**Pull request by fahlmant**
In order for cluster service to use these policies with the rosa cli, the names of the files need to change. See linked Jira card for more details
https://issues.redhat.com/browse/OSD-15496

### CODE REVIEW

**Review by jewzaam — CHANGES_REQUESTED** [review]
Taking the original file names as correct I'd expect:
* `ControlPlaneOperatorPolicy.json` --> `sts_hcp_control_plane_operator_permission_policy.json`
* `ROSAImageRegistryOperator.json` --> `sts_hcp_image_registry_operator_permission_policy.json`

**Review by jewzaam — APPROVED** [review]
/lgtm

**Comment by pvasant** [comment]
can we change the name of the openshift_hcp_worker_instance_permission_policy.json account role policy to  
 sts_hcp_instance_worker_permission_policy.json

**Comment by pvasant** [comment]
i guess it is me. Can we add hcp prefix please  thsresources/sts/4.12/hypershift/openshift_**hcp**_capa_controller_manager_credentials_policy.json

**Comment by fahlmant** [comment]
@pvasant I copied what was in the Jira directly. Can you please update it with the name you expect?

**Comment by fahlmant** [comment]
updated according to jira

**Pull request merged**
