### PR TITLE
Configure staging endpoint for insights

### PR DESCRIPTION
**Pull request by cblecker**
### What type of PR is this?
bug

### What this PR does / why we need it?
This configures the endpoint for the staging/integration environments for insights. While it is a `Secret` object, the endpoint URL isn't actually secret.

### Which Jira/Github issue(s) this PR fixes?
related to [RHCLOUD-17289](https://issues.redhat.com/browse/RHCLOUD-17289), [OHSS-11241](https://issues.redhat.com//browse/OHSS-11241)

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by dofinn** [comment]
@cblecker are there docs illustrating instructions to achieve this?

**Comment by cblecker** [comment]
@dofinn https://issues.redhat.com/browse/OHSS-11241?focusedCommentId=20089408&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-20089408

But it won't fully start working until https://issues.redhat.com/browse/RHCLOUD-17289?focusedCommentId=20437711&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-20437711

**Comment by dofinn** [comment]
The docs don't specify the use of a "secret" called "support" in "openshift-config". 

The ohss specifies "https://cloud.staging.redhat.com/api/ingress/v1/upload" but the base64 string in this PR is: "https://cloud.stage.redhat.com/api/ingress/v1/upload"

Can you please clarify then we can merge and await on RHCLOUD-17289

**Comment by cblecker** [comment]
@dofinn I have already verified this in a stage cluster (both the URL and the proper placement of the config.

**Pull request merged**
