### PR TITLE
Allow dedicated-admins to see "Dashboards" link in console under "Monitoring"

### PR DESCRIPTION
**Pull request by jewzaam**
https://issues.redhat.com/browse/OSD-3295

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm
/approve
/hold

Should we note that this can be removed post 4.4 upgrade?

**Comment by wanghaoran1988** [comment]
> Should we note that this can be removed post 4.4 upgrade?

Could you point me why this can be removed post 4.4 upgrade?

**Comment by jewzaam** [comment]
@wanghaoran1988 & @cblecker tracking reverting this in https://issues.redhat.com/browse/OSD-3301

**Comment by jewzaam** [comment]
@cblecker given we are tracking the revert could we remove the hold?

**Pull request merged**
