### PR TITLE
Add option to install local pre-push hook to run PR check

### PR DESCRIPTION
**Pull request by jewzaam**
My last 4 PRs I not run `make`.  It annoyed me so I made a simple pre-push hook for myself.
This PR shares it with others with a way to install and docs.

### CODE REVIEW

**Comment by jewzaam** [comment]
Fun side note, I had done the pre-push hook in a branch that would fail pushing.  Upon attempting to push to mcc it failed locally!  And then I fixed it all back to where it should be.. it surprised me to see it run at first because it's verbose but it did its job.

**Comment by RiRa12621** [comment]
i'd like to see .git/hooks/ added to gitignore so no one has issues constantly checking that in

**Comment by jewzaam** [comment]
@RiRa12621 `.git` is ignored by default, it's where git adds all its things..

**Pull request merged**
