### PR TITLE
 [ ODD - 9141 ] MUO's cluster-config role/binding as a workaround for CSV permissions issue

### PR DESCRIPTION
**Pull request by a7vicky**
https://issues.redhat.com/browse/OSD-9141
As a workaround, this selectorsyncset will create that role and rolebinding.

### CODE REVIEW

**Comment by mrbarge** [comment]
/hold
To be tested in conjunction with https://github.com/openshift/managed-upgrade-operator/pull/294

**Comment by mrbarge** [comment]
@a7vicky can you please:
- add an `OWNERS` file is defined in the base directory that matches that of `managed-upgrade-operator-config`.
- add a `README.md` that describes the reason for each role being added.

**Comment by fahlmant** [comment]
cloud-ingress-operator also does this, but uses the olm-artifacts-template.yaml SelectorSyncSet: https://github.com/openshift/cloud-ingress-operator/blob/master/hack/olm-registry/olm-artifacts-template.yaml#L168-L481

This ensures the rbac for CIO is also still in its own repo. Could this be moved to the MUO equivalent? https://github.com/openshift/managed-upgrade-operator/blob/master/hack/olm-registry/olm-artifacts-template.yaml

**Comment by a7vicky** [comment]
Thanks @fahlmant  
I have followed the same strategy to have role,rolebindings as part of MUO repo.

**Pull request closed without merging**
