### PR TITLE
changed severity level of SLAUptimeSRE alert

### PR DESCRIPTION
**Pull request by sulmer-redhat**
OSD-4517

/hold @jewzaam commented:
 "Holding until we have https://issues.redhat.com/browse/OSD-4414 addressed (SOP on this alert). The big question I have is "what actions does SRE take when this alert fires?" and it's not yet answered so we cannot hit on-call with this as a critical alert yet."

### CODE REVIEW

**Comment by jewzaam** [comment]
/approve

Just pending the SOP as noted.

**Comment by NautiluX** [comment]
SOP in place now. This PR will need rebase, corresponding ticket in OSD unblocked.

**Comment by bdematte** [comment]
It would be good to add the link to the SOP now it exists to ease investigations.

**Comment by NautiluX** [comment]
the SOP is at the default place for the alert, so it should work.

**Comment by dofinn** [comment]
https://github.com/openshift/ops-sop/blob/master/v4/alerts/SLAUptimeSRE.md 
+1 from me. Will let others way in.

**Comment by NautiluX** [comment]
@superfunhappytime this is the PR to raise the severity of the alert. I understand the original purpose was only for a dashboard creation. However, if we breach the SLA, that will be a heavy symptom so I would assume an alert is appropriate. We created an SOP for getting started debugging API server failures, and most probably this alert won't come without any context at warning or info level, so I would really think it is quite actionable.

**Comment by dofinn** [comment]
FYI, there is also this https://github.com/openshift/configure-alertmanager-operator/blob/master/pkg/controller/secret/secret_controller.go#L125

**Comment by NautiluX** [comment]
well that's an interesting find @dofinn

**Comment by RiRa12621** [comment]
https://github.com/openshift/configure-alertmanager-operator/pull/136
to remove the silence

**Comment by jharrington22** [comment]
@NautiluX @dofinn @RiRa12621 @bdematte 

I'm in favor of changing this to critical but before that can happen the SOP needs to have more actionable content. As an SRE once I run the `crictl ps` and `crilogs` commands, verify etc and networking whats next? The AWS status page almost never shows actual problems. 

Should the result of this be an OHSS ticket?

**Comment by RiRa12621** [comment]
had conversation with @jharrington22 offline about this: we need to have a proper policy for this SLO, that can be linked for to the SOP so it's crystal clear
I'll set something up next week to define one

**Comment by RiRa12621** [comment]
let's move ahead with this and at the same time kick off the conversation again on a potential policy

**Comment by NautiluX** [comment]
just realized this still has a hold. @ramonbutter @sulmer-redhat can you check and `\ unhold` when you're ready to merge?

**Pull request merged**
