### PR TITLE
OSD-16361: Deprecate custom-domains-operator if legacy-ingress-support label is available 

### PR DESCRIPTION
**Pull request by samanthajayasinghe**
### What type of PR is this?
feature

### What this PR does / why we need it?
Remove  custom-domains-operator resources if legacy-ingress-support label is available.

4.13+ clusters will include `legacy-ingress-support: "false" ` label and CDO, and its resources may not be deployed to new clusters. 

### Which Jira/Github issue(s) this PR fixes?

https://issues.redhat.com/browse/OSD-16361

### Pre-checks (if applicable):
- [x] Tested latest changes against a cluster
- [] Included documentation changes with PR
- [x] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Review by hectorakemp — APPROVED** [review]
Great work @samanthajayasinghe ! Ready for a spin on stage, I think.

**Comment by bmeng** [comment]
Why do we need to change the files other than [deploy/osd-custom-domains/config.yaml] ?

**Comment by hectorakemp** [comment]
> Why do we need to change the files other than [deploy/osd-custom-domains/config.yaml] ?

@bmeng - several other SSS are failing because the `openshift-custom-domains-operator` namespace isn't installed when this feature is toggled on. See this clustersync:
```
    - failureMessage: 'failed to apply resource 11: error when creating "object":
        namespaces "openshift-custom-domains-operator" not found'
      lastTransitionTime: "2023-07-17T05:20:30Z"
      name: osd-rebalance-infra-nodes
      observedGeneration: 17
```
    - failureMessage: 'failed to apply resource 0: error when creating "object": namespaces
        "openshift-custom-domains-operator" not found'
      lastTransitionTime: "2023-07-17T05:14:32Z"
      name: osd-serviceaccounts-aws
      observedGeneration: 2
      result: Failure
```

**Comment by samanthajayasinghe** [comment]
> > Why do we need to change the files other than [deploy/osd-custom-domains/config.yaml] ?
> 
> @bmeng - several other SSS are failing because the `openshift-custom-domains-operator` namespace isn't installed when this feature is toggled on. See this clustersync:
> 
> ```
>     - failureMessage: 'failed to apply resource 11: error when creating "object":
>         namespaces "openshift-custom-domains-operator" not found'
>       lastTransitionTime: "2023-07-17T05:20:30Z"
>       name: osd-rebalance-infra-nodes
>       observedGeneration: 17
> ```
> 
> ```
> - failureMessage: 'failed to apply resource 0: error when creating "object": namespaces
>     "openshift-custom-domains-operator" not found'
>   lastTransitionTime: "2023-07-17T05:14:32Z"
>   name: osd-serviceaccounts-aws
>   observedGeneration: 2
>   result: Failure
> ```



> Why do we need to change the files other than [deploy/osd-custom-domains/config.yaml] ?

Thanks @hectorakemp , As Hector explains. it's necessary to restrict other objects with  `legacy-ingress-support`  condition

**Pull request merged**
