### PR TITLE
Patch cluster Ingress.config to enable HTTP/2

### PR DESCRIPTION
**Pull request by fahlmant**
Enable HTTP/2 

Reference [OSD-5521](https://issues.redhat.com/browse/OSD-5521) https://issues.redhat.com/browse/OSD-5521

### CODE REVIEW

**Comment by cblecker** [comment]
/hold
We can only do this in 4.5+, right?

**Comment by fahlmant** [comment]
@cblecker Yep, but this should hit stage first right?

**Comment by cblecker** [comment]
We can add in restrictions to only deploy to certain versions programatically:

```
deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: hive.openshift.io/version-major-minor
    operator: NotIn
    values: ["4.3","4.4","4.5"]
```

**Comment by jharrington22** [comment]
@cblecker good idea but we want to include 4.5 and make sure we exclude `["4.0","4.1","4.2","4.3","4.4"]` ? 

There is a small list of clusters not at 4.5 which I'll add to the ticket, we should understand why they aren't upgraded.

**Comment by cblecker** [comment]
/lgtm
/approve

Seems sane to me. @fahlmant feel free to `/hold cancel` when you're ready for this to merge to stage

**Pull request merged**
