### PR TITLE
Updated OSD branding

### PR DESCRIPTION
**Pull request by jewzaam**
https://issues.redhat.com/browse/OSD-3122

Attempt #2, blocking issue https://issues.redhat.com/browse/CO-379 is fixed.

### CODE REVIEW

**Comment by jewzaam** [comment]
Note, previous attempt at this is https://github.com/openshift/managed-cluster-config/pull/327 which was reverted in https://github.com/openshift/managed-cluster-config/pull/360 due to https://issues.redhat.com/browse/CO-379

**Comment by cblecker** [comment]
/lgtm
/hold

Round 2? Heh. Feel free to release the hold whenever you're ready @jewzaam.

I was able to check out this branch, and test it on my test cluster with the following:
```
oc replace -f deploy/osd-oauth-templates-errors/osd-oauth-templates-errors.secret.yaml -f deploy/osd-oauth-templates-login/osd-oauth-templates-login.secret.yaml -f deploy/osd-oauth-templates-providers/osd-oauth-templates-providers.secret.yaml
```

**Pull request merged**
