### PR TITLE
Remove openshift-sre-sshd namespace from hives

### PR DESCRIPTION
**Pull request by fahlmant**
### What type of PR is this?
Cleanup

### What this PR does / why we need it?
Removes the SSHD namespace deployment from hive 
### Which Jira/Github issue(s) this PR fixes?

https://issues.redhat.com//browse/OSD-11724

### Special notes for your reviewer:

Dependent on https://github.com/openshift/managed-cluster-config/pull/1163 merging

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by fahlmant** [comment]
/hold 
until https://github.com/openshift/managed-cluster-config/pull/1163 is merged

**Comment by cblecker** [comment]
@fahlmant can you also remove `config.yaml` from this folder too?

**Comment by fahlmant** [comment]
@cblecker That would also remove the infra node placement patch from here right? https://github.com/openshift/managed-cluster-config/blob/master/deploy/osd-ingress/controller/router-infraNodes.patch.yaml

**Pull request merged**
