### PR TITLE
Removal of CSSRE and MTSRE groups

### PR DESCRIPTION
**Pull request by pat-cremin**
### What type of PR is this?
Feature

### What this PR does / why we need it?
With the usage of LPSRE the former MTSRE and CSSRE groups should no longer be needed. 

### Which Jira/Github issue(s) this PR fixes?
[MTSRE-1409](https://issues.redhat.com//browse/MTSRE-1409)

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Comment by Ankit152** [comment]
@pat-cremin can you squash the commits?
The PR looks good to me. 🙂

**Comment by pat-cremin** [comment]
@mrbarge @fahlmant can I get you to review this please?

**Review by NautiluX — COMMENTED** [review]
/lgtm

**Pull request merged**
