### PR TITLE
Add PR check to detect changes to rolerefs in rolebindings/clusterrolebingings

### PR DESCRIPTION
**Pull request by karthikperu7**
[OSD-6084]

I will make an illegal change in this PR to show that the PR check works (and fails) and remove the change afterwards.

### CODE REVIEW

**Comment by karthikperu7** [comment]
/hold
for PR check on a dummy illegal change

**Comment by karthikperu7** [comment]
Temporary illegal change: https://github.com/openshift/managed-cluster-config/pull/622/commits/7ad0878ba20aee427fc96ff0fc1b2669a045b24c#diff-d7b77c181e7b815ca73cbccd27add0d0830af3a397967a06260df969f29f6fb8L10

Resulting failed PR check: [ci.ext.devshift#1726](https://ci.ext.devshift.net/job/openshift-managed-cluster-config-gh-pr-check/1726/console)

**Comment by RiRa12621** [comment]
The reason here is that rolerefs can't be changed.
It's cool that we notice on the PR check but I'd appreciate a small line or link to docs on how remove a role and create a new one with MCC

**Comment by jewzaam** [comment]
@karthikperu7 good point from @RiRa12621 , having a quick SOP linked that says what to do instead will be very helpful.  Or rewording the error.  But an SOP gives a place for us to tweak wording and add context without impacting the PR check over time.

/approve

**Pull request merged**
