### PR TITLE
OSD-9131 OSD-8791 cluster proxy alerting

### PR DESCRIPTION
**Pull request by dofinn**
This PR enables alerting for the conditions of:

- proxy CA expiring in less then 30 days - warning
- proxy CA expiring in less then 15 days - critical
- proxy CA failed validation - warning

These will need to hit the pager and be service logged manually until ocm-agent is ready. 

SOPS will be provided later as not a priority against change freeze deadline. 

This PR should not be merged until https://github.com/openshift/osd-metrics-exporter/pull/72 is in production.

### CODE REVIEW

**Comment by dofinn** [comment]
/hold 

pending https://github.com/openshift/osd-metrics-exporter/pull/72

**Comment by mrbarge** [comment]
I'm not personally sold on the idea that `ClusterProxyCAExpiringSRE` becomes a critical 15 days out because it's not a critical situation for SRE or the cluster, and the responsibility currently falls on the cluster owner to do their due diligence in keeping tabs on their cluster CA. 

I would be more inclinced to have a critical `ClusterProxyCAExpiredSRE` which occurs once the CA has actually expired, as that can have actual impact to the cluster's operational ability and health, and will likely be the harbinger of future issues.

**Comment by dofinn** [comment]
@mrbarge thanks for feedback. I use the proposed conditions in light of how a customer will receive them via service log, so they may receive the warning and forget/do-nothing, but then they receive a critical and should act. We can also add expired if we like ? else i think the Critical sev covers that case.

**Comment by mrbarge** [comment]
I have made some SOP changes here to cater for these PRs:
https://github.com/openshift/ops-sop/pull/1652
@dofinn if you could give that PR a quick look to ensure it lines up with what is being done here, that'd be great.

/lgtm

**Pull request merged**
