### PR TITLE
Fix provisioner for gcp ssd storageclass

### PR DESCRIPTION
**Pull request by cblecker**

### CODE REVIEW

**Comment by jharrington22** [comment]
@cblecker I confirmed that this wasn't working in its original implementation PVC's were failing to create. After flipping it to `gce-pd` PVC's started working.

/lgtm

**Review by jharrington22 — APPROVED** [review]

**Comment by jharrington22** [comment]
Performance analysis is with standard storage and then the new SSD performance

```
Standard storage

==================
= Dbench Summary =
==================
Random Read/Write IOPS: 147/299. BW: 16.5MiB/s / 29.7MiB/s
Average Latency (usec) Read/Write: 26.35/13156.52
Sequential Read/Write: 109MiB/s / 107MiB/s
Mixed Random Read/Write IOPS: 127/41

New SSD storageclass disk performance
# 100Gb
==================
= Dbench Summary =
==================
Random Read/Write IOPS: 9939/6831. BW: 159MiB/s / 159MiB/s
Average Latency (usec) Read/Write: 529.84/920.24
Sequential Read/Write: 155MiB/s / 154MiB/s
Mixed Random Read/Write IOPS: 7399/2465
```

**Comment by dustman9000** [comment]
@aliceh - has manually verified these changes on a GCP cluster.
/hold cancel

**Pull request merged**
