### PR TITLE
feat(osd-devaccess): allow project creation

### PR DESCRIPTION
**Pull request by georgettica**
this will allow project creation for must gathers purposes

### CODE REVIEW

**Comment by dofinn** [comment]
@georgettica do we need to add delete see dev-access can clean up after themselves? They should only be able to delete namespaces they created.

**Comment by cblecker** [comment]
@dofinn I believe privs are automatically granted to namespaces you own to delete. I don't think we need to add extra.

**Comment by georgettica** [comment]
I agree with @cblecker , when a project is created.by a user he receives an Admin role to it, so he can delete it when he is done

**Comment by georgettica** [comment]
closing as a solution was devised in #584

**Pull request closed without merging**
