### PR TITLE
Adding CS-SRE Interns

### PR DESCRIPTION
**Pull request by g0ldrush**

### CODE REVIEW

**Comment by dofinn** [comment]
@g0ldrush , Please run `make` and resubmit your changes. 
RE: https://github.com/openshift/managed-cluster-config#how-to-use-this-repo

**Comment by jewzaam** [comment]
There is an alternative to this individual property way of doing this you could use.  See https://github.com/openshift/managed-cluster-config/blob/master/deploy/osd-devaccess/00-osd-devaccess.Group.yaml#L5 and the syntax in the template in app-interface for this is:

```
services:
- ...
  environments:
  - name: production
    parameters:
      CEE_USERS:
      - someuser
      - anotheruser
      - myfavoriteuser
...
```

**Comment by g0ldrush** [comment]
@jewzaam , will look at your proposed changes next time I add/remove users.

**Pull request merged**
