### PR TITLE
Allow ROSANodePoolManagementPolicy to reconcile tags on ENIs

### PR DESCRIPTION
**Pull request by mjlshen**
### What type of PR is this?
bug

### What this PR does / why we need it?

This is for the [egressIP feature](https://docs.openshift.com/rosa/cloud_experts_tutorials/cloud-experts-consistent-egress-ip.html) of the cluster-network-operator. It relies on performing actions against network interface (ENI) objects in AWS. However, its [AWS Managed Policy](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/ROSACloudNetworkConfigOperatorPolicy.html) only allows it to perform actions against ENIs with the `red-hat-managed: true` tag and none of the worker node ENIs of ROSA HCP clusters have this tag

cluster-api-provider-aws is already trying to tag the ENIs after creation https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/0baa03c61701a287678b0ac83b66a8018886e54f/pkg/cloud/services/ec2/instances.go#L294-L303, however the ROSANodePoolManagementPolicy does not have the necessary AWS permissions.

This PR fixies this bug on the ROSANodePoolManagementPolicy Managed Policy:

#### Allow CAPA to reconcile tags on ENIs
* CAPA has been trying to tag ENIs, however this has not been allowed by
  our managed policy and considered non-impactful
* However, recently we realized that this prevents the egressIP feature
  from working and this PR fixes this bug

### Which Jira/Github issue(s) this PR fixes?
[OSD-19650](https://issues.redhat.com//browse/OSD-19650)

### Pre-checks (if applicable):
- [x] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Comment by mjlshen** [comment]
/hold

For discussion/alignment among stakeholders with this card

**Review by fahlmant — COMMENTED** [review]
We have permissions for instances and volumes in both "CreateTags" and "CreateTags for RunInstances". Can we add network-interface to both to be consistent?

**Review by mjlshen — COMMENTED** [review]
I've tested this again after the latest changes by installing a ROSA HCP cluster and validating that its worker node ENIs get tagged. Then, following the egressIP documentation to validate that the expected functionality works as well https://docs.openshift.com/rosa/cloud_experts_tutorials/cloud-experts-consistent-egress-ip.html

**Comment by mjlshen** [comment]
Superceded by #2170

**Pull request closed without merging**
