### PR TITLE
Revert osd-customer-monitoring openshift-acme

### PR DESCRIPTION
**Pull request by rporres**
We finally couldn't make it work as openshift-acme demanded full control
over the secrets of the namespace, including deleting them.

This reverts commit 2db9003ed7eff70619fa7fe4d3d0bceccae13d9a.
This reverts commit f9f5e4c17359e40f9185b5af69f1703ace84dc26.
This reverts commit ac11d330c9576567f8102c06c85e95d73428fb65.

### CODE REVIEW

**Comment by cblecker** [comment]
/assign @rogbas @jewzaam @mwoodson 
Assigning Rogerio/Naveen/Matt who approved the original PRs

**Comment by jewzaam** [comment]
@rporres not sure who is using this capability, removing rbac could break them.  Is there more context on why this won't be a problem to merge?  Thanks.

**Comment by rporres** [comment]
App-SRE (actually @maorfr and me) introduced all those rules in an attempt to make [openshift-acme](https://github.com/tnozicka/openshift-acme) work in that namespace. We were the users for this RBAC rules but we're not going to use them that's why I have created this revert PR. I have no notice of this being used by anyone which is not a guarantee that they are not actually being used. If you don't have an issue with them being in place, I can just close this PR.

**Comment by jewzaam** [comment]
Good enough for me, thanks!

/lgtm
/approve

**Pull request merged**
