### PR TITLE
OSD-9072: added admin-acks README

### PR DESCRIPTION
**Pull request by ramonbutter**

### CODE REVIEW

**Review by georgettica — APPROVED** [review]

**Comment by georgettica** [comment]
/approve
/lgtm
I don't see why this would hurt

**Review by fahlmant — COMMENTED** [review]
Please add an OWNERS file as well

**Comment by georgettica** [comment]
/hold
Unhold after owners file is added

**Comment by georgettica** [comment]
I guess that's a good start :(

**Pull request merged**
