### PR TITLE
Add 'operators.coreos.com' api permissions to backplane lpsre

### PR DESCRIPTION
**Pull request by nikhil-thomas**
Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

Add permissions for 'operators.coreos.com' to lpsre and mtsre olm api roles

**jira**

- https://issues.redhat.com/browse/MTSRE-933
- https://issues.redhat.com/browse/MTSRE-834

### CODE REVIEW

**Comment by jewzaam** [comment]
/hold

What is the justification for this (i.e. JIRA)?  I have never touched this CR when managing an operator that I can recall.  It has only a status.  Providing the ability to update this CR is questionable.

**Comment by nikhil-thomas** [comment]
i agree. I have limited the permissions to `get`, `list`, `watch`.

**Review by jewzaam — CHANGES_REQUESTED** [review]
/hold cancel
/approve

Please run `make`.

**Pull request merged**
