### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by RiRa12621**
add @NautiluX to approvers

### CODE REVIEW

**Comment by cblecker** [comment]
Don't we usually add folks to reviewers first?

**Comment by RiRa12621** [comment]
Does it make a difference?

**Comment by jewzaam** [comment]
/hold
Would like to hear justification for this change please.

**Comment by RiRa12621** [comment]
Need a second person in this timezone as I can’t approve my own things

**Comment by cblecker** [comment]
> Need a second person in this timezone as I can’t approve my own things

If you open a PR, yes, you should automatically get the approved label. Anyone can LGTM a PR.

**Comment by jewzaam** [comment]
More importantly if @RiRa12621 isn't available there's nobody in the TZ to approve things, which can really delay things.  If Rick is OK w/ this and wants it I'm good with it too.  Just wanted to check since it's not how folks usually make it to the approvers list.

/lgtm
/approve
/hold cancel

**Pull request merged**
