### PR TITLE
add bootstrapping hackdir

### PR DESCRIPTION
**Pull request by aweiteka**
Signed-off-by: Aaron Weitekamp <aweiteka@redhat.com>

### CODE REVIEW

**Comment by aweiteka** [comment]
I was thinking we could add @jewzaam 's [auth config](https://github.com/jewzaam/managed-cluster-config/tree/osd-sre-admin/generate/sre-authorization) as well as any operator bootstrapping commands and scripts.

**Comment by jewzaam** [comment]
This looks broader than `managed-cluster-config`.  Perhaps better suited as an SOP where we have a "Here's how to make OCP4 OSD4 with `oc`"?

**Comment by aweiteka** [comment]
@jewzaam apologies for the massive PR. This appears more consistent with the goals of deploy dir. Added a simple HACK.md file on manually deploying these manifests.

**Comment by jewzaam** [comment]
Deployment of components is managed outside of this repo, closing this PR.

**Pull request closed without merging**
