### PR TITLE
Remove RHOSAK and RHOC

### PR DESCRIPTION
**Pull request by robshelly**
### What type of PR is this?
_cleanup_
Remove discontinued services RHOSAK and RHOC

### Which Jira/Github issue(s) this PR fixes?

_Fixes #_

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Comment by Nanyte25** [comment]
@fahlmant or @dustman9000 can you approve?

**Comment by robshelly** [comment]
@tonytheleg Can this be merged please?

**Review by mjlshen — APPROVED** [review]
/lgtm

**Pull request merged**
