### PR TITLE
Remove ExcessiveContainerMemory alerts

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <yb532204897@gmail.com>

https://issues.redhat.com/browse/OSD-4439

The alerts `ExcessiveContainerMemoryWarningSRE` and `ExcessiveContainerMemoryCriticalSRE` have hardcoded limits which are not good for alerting.

### CODE REVIEW

**Comment by cblecker** [comment]
These alerts were added for a reason as well.

cc @jewzaam

**Comment by RiRa12621** [comment]
iirc the reason was a memory leak in one of the OCP components @cblecker , which should be fixed by now.

**Comment by RiRa12621** [comment]
@cblecker can we move ahead with this or not?

**Comment by NautiluX** [comment]
@cblecker I don't think having an alert for a static amount of memory used is a good long-term solution to detect memory leaks. Should we create a card to ensure every pod we run in the watched namespaces have limits set before we remove the alert?

**Comment by RiRa12621** [comment]
@cblecker can we move ahead with this or not?

**Comment by RiRa12621** [comment]
Yes, no, maybe?

**Pull request closed without merging**
