### PR TITLE
Remove alert AlertmanagerSilencesActiveSRE

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <yb532204897@gmail.com>

https://issues.redhat.com/browse/OSD-4432

This alert prevents us from silencing anything to the cluster.

### CODE REVIEW

**Comment by RiRa12621** [comment]
/unhold
this was discussed in a meeting on monday with @jharrington22 @jewzaam and @mwoodson and needs to be dropped as our general agreement is move to silences to "on cluster" in the future.
This alerting rule would prevent such workflow.
/lgtm

**Comment by yeya24** [comment]
@NautiluX @jewzaam Hello, would you mind taking a look at this issue?

**Comment by jewzaam** [comment]
@RiRa12621 @cblecker we discussed this a few weeks ago, I didn't realize at the time we do suppress this alert while in upgrade.  We do need to create silences in cluster but should only need that for upgrades.  Would SRE not use PD maint for anything outside of an upgrade?

Note that the metric used for detecting upgrade `cluster_version{type="upgrading"}` will only cover control plane, not node upgrades.  @dofinn 

Given this, I think it's reasonable to keep the alert.  We do not want customers creating silences and SRE has other tools to create ad-hoc silences in a central system (PagerDuty).

**Comment by RiRa12621** [comment]
There's two things here: one I remember seeing a card that said to move all silences to in cluster and two how would we silence a single alert for a cluster
A potential case here is a flapping alert a customer is causing but is informed about and working on.
We could easily silence that in cluster but I'm not sure how to in PagerDuty

**Comment by RiRa12621** [comment]
/close
https://github.com/openshift/managed-cluster-config/pull/401#issuecomment-665171172
Clearly no perspective of this ever getting merged

**Pull request closed without merging**
