### PR TITLE
Remove efried per Leaver process

### PR DESCRIPTION
**Pull request by billmvt**
see https://issues.redhat.com/browse/OHSS-4669

### CODE REVIEW

**Comment by dofinn** [comment]
Thanks @billmvt . Looks like we also need to remove from custom domains?

```
rg '2uasimojo'                                                                                                                            ✔  4s  !1/15  
deploy/osd-custom-domains/OWNERS
4:- 2uasimojo

OWNERS_ALIASES
20:    - 2uasimojo
```

**Comment by billmvt** [comment]
Per @dofinn 's comment on 14-Jun, efried was already removed from deploy/osd-custom-domains/OWNERS on 14-Jun in this commit: https://github.com/openshift/managed-cluster-config/commit/72b4027806b0e01dd6870b9fcc7c9bbae7cda333

@wanghaoran1988 or @dofinn please to approve & merge?

**Pull request merged**
