### PR TITLE
Add policies for 4.10

### PR DESCRIPTION
**Pull request by pvasant**
https://issues.redhat.com/browse/SDA-5683

We need to reconcile all the latest policy from ROSA cli to MCC repo so app-interface can read it from and feed to CS

### CODE REVIEW

**Comment by pvasant** [comment]
@cblecker @jharrington22 @vkareh PTAL

**Comment by fahlmant** [comment]
Please add a description

**Comment by pvasant** [comment]
> Please add a description

Done. Can you please review

**Review by fahlmant — COMMENTED** [review]
Looks good generally. Is there also a set for a PrivateLink installation? 
https://github.com/openshift/managed-cluster-config/tree/master/resources/privatelink

**Comment by pvasant** [comment]
@fahlmant  yes i see we already have those permissions 

```
"ec2:DescribeVpcEndpointServiceConfigurations",
                "ec2:CreateVpcEndpointServiceConfiguration",
                "ec2:DescribeVpcEndpointServicePermissions",
                "ec2:DeleteVpcEndpointServiceConfigurations",
                "ec2:ModifyVpcEndpointServicePermissions",
                "ec2:DescribeVpcEndpointServices"
```

**Comment by fahlmant** [comment]
@pvasant We need a set of 4.10 permissions that are specific to PrivateLink.

**Comment by pvasant** [comment]
> @pvasant We need a set of 4.10 permissions that are specific to PrivateLink.

What are those? I see only those six permissions in the link you shared. Can you please send me those extra permissions i can add it.

**Comment by pvasant** [comment]
> @pvasant We need a set of 4.10 permissions that are specific to PrivateLink.

Ok i see what you are saying. Yeah but CS or ROSA or app-interface doesnt care about that folder. I can add this to the MR

**Comment by fahlmant** [comment]
Because PrivateLink and Standard STS clusters require different permissions. For example, PrivateLink installs don't need permissions to create VPCs, Subnets, etc. The point of STS is least privilege, so anytime an STS cluster is installed via PrivateLink it should use those policies instead. The rosa cli should be using these for those cases

**Review by jharrington22 — APPROVED** [review]
/lgtm

**Pull request merged**
