### PR TITLE
OSD-13914 - Fixing the syntax for resource patch for cluster oauth

### PR DESCRIPTION
**Pull request by bdematte**
### What type of PR is this?
Bug

### What this PR does / why we need it?
Update syntax for the patching action

### Which Jira/Github issue(s) this PR fixes?
[OSD-13914](https://issues.redhat.com//browse/OSD-13914)

### Special notes for your reviewer:
Tested the patching on a standard OSD cluster which initially showed similar error when trying to apply the 'patch' 

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Comment by cblecker** [comment]
Isn't this a generated resource?
/hold

**Comment by bdematte** [comment]
@cblecker The initial version (to help migrating) was generated with the script, but it has been removed from the generator config (and moved to a dedicated folder) so isn't anymore. 
I will rename it in a dedicated MR to avoid future confusion.

**Comment by cblecker** [comment]
@bdematte Why aren't we generating it? Won't that mean config between stand-alone and HS could drift?

**Comment by bdematte** [comment]
Having a working version now, I think it makes sense. I still have some issues related to oauth (unrelated to this MR) to investigate, but I will ensure we have generators for all resources once I know what is the target for those files.

**Pull request merged**
