### PR TITLE
Add CSSRE permissions to scale operator deployment

### PR DESCRIPTION
**Pull request by robshelly**
### What type of PR is this?
_feature_

### What this PR does / why we need it?
Gives CSSRE permission to scale RHOAM deployment as the sometimes need to be scaled down to debug incidents.

### Which Jira/Github issue(s) this PR fixes?
https://issues.redhat.com/browse/CSSRE-1835

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by jewzaam** [comment]
/hold

This was modified in the srep permissions.
And the scope of what can be scaled is cluster wide.
The intent in CSSRE-1835 is to enable scaling of RHOAM related operators.

**Review by jewzaam — CHANGES_REQUESTED** [review]
Scope needs to be for CSSRE and focus on RHOAM only per CSSRE-1835.

**Comment by robshelly** [comment]
:man_facepalming: Fixed the mistake. Modified the correct file now. Thanks

**Review by jewzaam — CHANGES_REQUESTED** [review]
Need to run `make` to generate updated templates.

**Review by jewzaam — APPROVED** [review]

**Pull request merged**
