### PR TITLE
Change prometheus retention to 7 days

### PR DESCRIPTION
**Pull request by dofinn**
Context: https://issues.redhat.com/browse/OSD-4875

### CODE REVIEW

**Comment by RiRa12621** [comment]
I'd honestly rather see us using bigger volumes instead of reducing the retention further

**Comment by dofinn** [comment]
IMO we should increase volume/retention by requirement. This PR is a quick win to remove the alert we can do nothing about. Do we have cases where people want longer retention?

**Comment by RiRa12621** [comment]
You can barely see anything with 7 days of metrics 
Also we currently don't have means to increase volumes on a case by case basis

**Comment by georgettica** [comment]
woot!

**Pull request merged**
