### PR TITLE
OSD-7719 - least privilege permissions for vanilla STS installation

### PR DESCRIPTION
**Pull request by bng0y**
+ aligning folder structure with [rosa/templates/policies](https://github.com/openshift/rosa/tree/master/templates/policies ).
+ removing permissions not required for vanilla installation
```
"iam:GetRolePolicy",
"iam:GetUser", 
"iam:ListAttachedRolePolicies", 
"iam:ListInstanceProfiles",
"iam:ListInstanceProfilesForRole",
"iam:ListRolePolicies",
"iam:ListUserPolicies",
"iam:SimulatePrincipalPolicy",
"iam:UntagRole",
"ec2:CopyImage",
"ec2:CreateVolume",
"ec2:CreateVpcEndpointServiceConfiguration",
"ec2:DeleteRoute",
"ec2:DeleteSnapshot",
"ec2:DeleteTags",
"ec2:DeleteVpcEndpointServiceConfigurations",
"ec2:DeregisterImage",
"ec2:DescribeInstanceCreditSpecifications",
"ec2:DescribeKeyPairs",
"ec2:DescribeVpcEndpointServiceConfigurations",
"ec2:DescribeVpcEndpointServicePermissions",
"ec2:DescribeVpcEndpointServices",
"ec2:ModifyInstanceAttribute",
"ec2:ModifySubnetAttribute",
"ec2:ModifyVpcEndpointServicePermissions"
"elasticloadbalancing:ApplySecurityGroupsToLoadBalancer",
"elasticloadbalancing:AttachLoadBalancerToSubnets",
"elasticloadbalancing:ConfigureHealthCheck",
"elasticloadbalancing:CreateLoadBalancerListeners",
"elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
"elasticloadbalancing:DescribeInstanceHealth",
"elasticloadbalancing:RegisterInstancesWithLoadBalancer",
"elasticloadbalancing:SetLoadBalancerPoliciesOfListener",
"sts:AssumeRole", 
"sts:AssumeRoleWithWebIdentity", 
"autoscaling:DescribeAutoScalingGroups",
"tag:UntagResources",
"route53:UpdateHostedZoneComment",
```

### CODE REVIEW

**Comment by jharrington22** [comment]
> * aligning folder structure with [rosa/templates/policies](https://github.com/openshift/rosa/tree/master/templates/policies).
> * removing permissions not required for vanilla installation
> 
> ```
> "iam:GetRolePolicy",
> "iam:GetUser", 
> "iam:ListAttachedRolePolicies", 
> "iam:ListInstanceProfiles",
> "iam:ListInstanceProfilesForRole",
> "iam:ListRolePolicies",
> "iam:ListUserPolicies",
> "iam:SimulatePrincipalPolicy",
> "iam:UntagRole",
> "ec2:CopyImage",
> "ec2:CreateVolume",
> "ec2:CreateVpcEndpointServiceConfiguration",
> "ec2:DeleteRoute",
> "ec2:DeleteSnapshot",
> "ec2:DeleteTags",
> "ec2:DeleteVpcEndpointServiceConfigurations",
> "ec2:DeregisterImage",
> "ec2:DescribeInstanceCreditSpecifications",
> "ec2:DescribeKeyPairs",
> "ec2:DescribeVpcEndpointServiceConfigurations",
> "ec2:DescribeVpcEndpointServicePermissions",
> "ec2:DescribeVpcEndpointServices",
> "ec2:ModifyInstanceAttribute",
> "ec2:ModifySubnetAttribute",
> "ec2:ModifyVpcEndpointServicePermissions"
> "elasticloadbalancing:ApplySecurityGroupsToLoadBalancer",
> "elasticloadbalancing:AttachLoadBalancerToSubnets",
> "elasticloadbalancing:ConfigureHealthCheck",
> "elasticloadbalancing:CreateLoadBalancerListeners",
> "elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
> "elasticloadbalancing:DescribeInstanceHealth",
> "elasticloadbalancing:RegisterInstancesWithLoadBalancer",
> "elasticloadbalancing:SetLoadBalancerPoliciesOfListener",
> "sts:AssumeRole", 
> "sts:AssumeRoleWithWebIdentity", 
> "autoscaling:DescribeAutoScalingGroups",
> "tag:UntagResources",
> "route53:UpdateHostedZoneComment",
> ```

@bng0y you're suggesting these are being removed?

**Comment by bng0y** [comment]
> > * aligning folder structure with [rosa/templates/policies](https://github.com/openshift/rosa/tree/master/templates/policies).
> > * removing permissions not required for vanilla installation
> > 
> > ```
> > "iam:GetRolePolicy",
> > "iam:GetUser", 
> > "iam:ListAttachedRolePolicies", 
> > "iam:ListInstanceProfiles",
> > "iam:ListInstanceProfilesForRole",
> > "iam:ListRolePolicies",
> > "iam:ListUserPolicies",
> > "iam:SimulatePrincipalPolicy",
> > "iam:UntagRole",
> > "ec2:CopyImage",
> > "ec2:CreateVolume",
> > "ec2:CreateVpcEndpointServiceConfiguration",
> > "ec2:DeleteRoute",
> > "ec2:DeleteSnapshot",
> > "ec2:DeleteTags",
> > "ec2:DeleteVpcEndpointServiceConfigurations",
> > "ec2:DeregisterImage",
> > "ec2:DescribeInstanceCreditSpecifications",
> > "ec2:DescribeKeyPairs",
> > "ec2:DescribeVpcEndpointServiceConfigurations",
> > "ec2:DescribeVpcEndpointServicePermissions",
> > "ec2:DescribeVpcEndpointServices",
> > "ec2:ModifyInstanceAttribute",
> > "ec2:ModifySubnetAttribute",
> > "ec2:ModifyVpcEndpointServicePermissions"
> > "elasticloadbalancing:ApplySecurityGroupsToLoadBalancer",
> > "elasticloadbalancing:AttachLoadBalancerToSubnets",
> > "elasticloadbalancing:ConfigureHealthCheck",
> > "elasticloadbalancing:CreateLoadBalancerListeners",
> > "elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
> > "elasticloadbalancing:DescribeInstanceHealth",
> > "elasticloadbalancing:RegisterInstancesWithLoadBalancer",
> > "elasticloadbalancing:SetLoadBalancerPoliciesOfListener",
> > "sts:AssumeRole", 
> > "sts:AssumeRoleWithWebIdentity", 
> > "autoscaling:DescribeAutoScalingGroups",
> > "tag:UntagResources",
> > "route53:UpdateHostedZoneComment",
> > ```
> 
> @bng0y you're suggesting these are being removed?
@jharrington22 for vanilla installation as documented [here](https://docs.openshift.com/rosa/rosa_getting_started_sts/rosa-sts-creating-cluster.html#rosa-sts-creating-cluster) yes. Since they are not required.

**Comment by fahlmant** [comment]
@bng0y its a bit hard to tell from the diff. Were these permission removed across all roles? Or just the installer-related roles?

**Comment by bng0y** [comment]
> @bng0y its a bit hard to tell from the diff. Were these permission removed across all roles? Or just the installer-related roles?

@fahlmant you make a good point. I can split the work into two parts if that will make it easier to review. 
- Part 1: align with rosa repo
- Part 2: update the permissions 
To answer your question, the permissions are only removed from the installer role.

**Comment by ritmun** [comment]
Regarding directory structure, what's the reason for putting the following files outside the version folders? Could these be placed inside a folder that signifies that reason? It might be easier to utilize these files as the source of truth in manual mode if we structure them that way. 

osd_scp_policy.json
sts_installer_trust_policy.json
sts_instance_controlplane_trust_policy.json
sts_instance_worker_trust_policy.json
sts_support_trust_policy.json

**Comment by bng0y** [comment]
> Regarding directory structure, what's the reason for putting the following files outside the version folders? Could these be placed inside a folder that signifies that reason? It might be easier to utilize these files as the source of truth in manual mode if we structure them that way.

@ritmun [rosa-cli](https://github.com/openshift/rosa/tree/master/templates/policies) has them in a different folder. Therefore, the intent was to align with the existing. 

My understanding is that since the policies don't change between versions, duplicating them was not necessary.

**Comment by fahlmant** [comment]
The policies can differ between versions though

**Comment by bng0y** [comment]
@fahlmant @ritmun as recommended, I duplicated the policies json in each version folder.

**Comment by fahlmant** [comment]
@bng0y Looks good. Keeping track of testing here

- [ ] Test 4.7 install with 4.7 permissions

- [ ] Test 4.8 install with 4.8 permissions

- [ ]  Test 4.9 install with 4.9 permissions

**Review by fahlmant — COMMENTED** [review]
Generally lgtm. I believe we're waiting on one more verification in OSD-8359. I'd like to test the 4.8 roles once more before approving.

**Review by fahlmant — APPROVED** [review]
/lgtm

**Pull request merged**
