### PR TITLE
Grant cluster wide imagestream READ permission to dedicated-admins

### PR DESCRIPTION
**Pull request by wanghaoran1988**
https://issues.redhat.com/browse/OSD-3294

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm
/approve
/hold

This looks good.. the one concern I have is double checking with the RHMI folks that they are cool with this change too. By default on OSD, we just have the system imagestreams in the `openshift` namespace.. I don't know if adding on RMHI changes that or if they have any concerns.

**Comment by wanghaoran1988** [comment]
Thanks @alanmoran
/hold cancel

**Pull request merged**
