### PR TITLE
Update of the generate logic for policies/SSS

### PR DESCRIPTION
**Pull request by lnguyen1401**
### What type of PR is this?
_(bug/feature/cleanup/documentation)_
cleanup/feature
### What this PR does / why we need it?
This PR includes:
1. moved over the generated resource to another directory 'generated_deploy', leaving deploy as a source of truth directory
2. Having a script that sweep all 'deploy' directories, if it's SSS then just copy that over to the 'generated_deploy', if it's policy then generate a policy and save that to the 'generated_deploy' directory.
3. Thus decommisioned generate-policy-config.py and generate-subjectpermissions-policy-config.py scripts
### Which Jira/Github issue(s) this PR fixes?
https://issues.redhat.com/browse/OSD-15563
_Fixes #_

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Review by rafael-azevedo — APPROVED** [review]
/lgtm

**Review by fahlmant — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
