### PR TITLE
Add Tailored Profile

### PR DESCRIPTION
**Pull request by Vincent056**
### What type of PR is this?
feature

### What this PR does / why we need it?

The tailored profiles here can be used by Compliance Operator to run the scan from the HyperShift management cluster to the Hosted cluster.

We added tailored profiles for PCI-DSS, and CIS benchmarks.

### Special notes for your reviewer:

There are a couple of rules failing with these tailored profiles, that we need to address here:

* hypershift-tailored-profile-api-server-encryption-provider-cipher ------ this will pass after [PR](https://github.com/ComplianceAsCode/content/pull/10179) is being merged
* hypershift-tailored-profile-api-server-encryption-provider-config ------ this will pass after [PR](https://github.com/ComplianceAsCode/content/pull/10179) is being merged
* hypershift-tailored-profile-audit-log-forwarding-enabled ------ is audit-log-forwarding enabled on the management cluster?
* hypershift-tailored-profile-configure-network-policies-namespaces ------ It is failing because there is no network policy for hosted control plane namespace
* pcidss-compliance-hypershift-file-integrity-exists ------ is File Integrity Operator being installed on the management cluster?
* pcidss-compliance-hypershift-file-integrity-notification-enabled ------ is File Integrity Operator being installed on the management cluster?
* pcidss-compliance-hypershift-kubeadmin-removed ------ is kubeadmin being removed?
* pcidss-compliance-hypershift-idp-is-configured ------ is an IdP being configured on the management cluster?

[Google Sheet Tracking the failing rules](https://docs.google.com/spreadsheets/d/1dqaA593u00eE6fKbYcKfNGbS7qm0T7LDxoIfpBMT_NI/edit#gid=1722570112)

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Comment by Vincent056** [comment]
@jewzaam we can disable some of the failing results here in the tailored profile if they can still meet compliance requirements, or remediate them so they will pass.

ex.
For rules related to FIO, we might be able to disable them since RHCOS is an immutable system, and it will still meet the compliance requirement.

**Comment by jewzaam** [comment]
@Vincent056 we should get anything for follow up created in JIRA so we can track it.  I take this PR as the baseline from which we'll modify to tune the profile over time and of course add new profiles as needed.

/approve

**Comment by Vincent056** [comment]
> @Vincent056 we should get anything for follow up created in JIRA so we can track it. I take this PR as the baseline from which we'll modify to tune the profile over time and of course add new profiles as needed.
> 
> /approve

Thanks, I have opened the ticket here: https://issues.redhat.com/browse/OSD-15157

**Pull request merged**
