### PR TITLE
Allow backplane users to run oc new-project

### PR DESCRIPTION
**Pull request by karthikperu7**
Turns out (backplane) service accounts don't get the `system:authenticated:oauth` group and therefore do not get perms to create projectrequests -> cannot run `oc new-project`. 

Therefore we have to explicitly enable this using RBAC.

cc: @jewzaam PTAL

### CODE REVIEW

**Comment by karthikperu7** [comment]
A little related to enablng MGO for backplane: https://issues.redhat.com/browse/OSD-5424

**Comment by jewzaam** [comment]
Projects are the domain of customers, without clear business reason why we need this for support teams I am closing this.  It was discussed on another PR to allow creation of project for must-gather operator use and it was not done as well, same reason.  Only customers should manage Projects.

**Comment by csheremeta** [comment]
@karthikperu7 we're going to rework MGO to accommodate the points that Naveen brought up

**Comment by karthikperu7** [comment]
@csheremeta & @jewzaam Thanks. This was mainly for MGO on backplane. If MGO wont need `oc new-project` to be run then we dont need this for cee.

**Pull request closed without merging**
