### PR TITLE
fix(maxunhealthy): bump count [OSD-6620]

### PR DESCRIPTION
**Pull request by georgettica**
this solves issues with bump upgrade

there would not be a bump from 3 -> 4 as 3 unhealthy nodes mean a bigger problem

### CODE REVIEW

**Comment by georgettica** [comment]
needs to be tested, after that the WIP will be removed

**Comment by georgettica** [comment]
blocked by code-freeze.

but it's fine because tests were not done yet

**Comment by georgettica** [comment]
stopping the 3 nodes in this case does work.
please review and merge when needed

**Comment by georgettica** [comment]
fixed make.
/retest

**Comment by georgettica** [comment]
no longer in WIP, works

**Comment by jharrington22** [comment]
@georgettica what OCP versions are you targeting?

**Comment by georgettica** [comment]
wasn't specific on versioning

I tested with `4.7.8` (the default version)

@jharrington22 should the version affect this card though?

**Comment by georgettica** [comment]
closing as this is not working.. trying above lastest

**Comment by jharrington22** [comment]
@georgettica the card doesn't mention a specific version. This change will not hit 4.7 clusters which is new the default.

**Comment by jharrington22** [comment]
Closing in favor of #806

**Pull request closed without merging**
