### PR TITLE
ROX-23697: add ACS-CS backplane console permissions

### PR DESCRIPTION
**Pull request by ludydoo**
### What type of PR is this?
_(feature)_

### What this PR does / why we need it?
- Allow ACS-CS SRE to use the `ocm backplane console` command

### Which Jira/Github issue(s) this PR fixes?

Fixes #[ROX-23697](https://issues.redhat.com//browse/ROX-23697)

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Comment by Nanyte25** [comment]
@jewzaam and @iamkirkbater

**Review by NautiluX — COMMENTED** [review]
/lgtm

**Review by NautiluX — COMMENTED** [review]
/lgtm

**Comment by Nanyte25** [comment]
@carlowisse or @fahlmant Can you approve this PR thank's

**Review by NautiluX — COMMENTED** [review]
/lgtm

**Pull request merged**
