### PR TITLE
Allow dedicated-admins to list 'thanosrulers'

### PR DESCRIPTION
**Pull request by aditya-konarde**
Closes: https://issues.redhat.com/browse/APPSRE-2461

thanosrulers is a new CRD added by the prometheus operator. Without this RBAC patch, the prometheus operator fails to watch CR's of this type and logs an error message along the lines of:

>E0909 14:13:01.999482 1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:316: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:openshift-customer-monitoring:prometheus-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" in the namespace "openshift-customer-monitoring"

### CODE REVIEW

**Review by RiRa12621 — APPROVED** [review]
/lgtm

**Review by NautiluX — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
