### PR TITLE
remove clusterlogging operatorgroup

### PR DESCRIPTION
**Pull request by RiRa12621**
We are allowing dedicated admins to install the operator as a whole and OLM has enough privileges to lay down the operatorgroup.
If we leave it like that, we run into conflicts with the operatorgroup coming via OLM as it has one more API

### CODE REVIEW

**Comment by RiRa12621** [comment]
/hold
need to test

**Comment by cblecker** [comment]
/lgtm
/approve
/hold

Is there a JIRA/bug for this Rick?

**Comment by RiRa12621** [comment]
It's part of the whole "unblock" logging upgrade

So no explicit ticket for just this.
Probably makes sense to have one

**Pull request closed without merging**
