### PR TITLE
feat(rbac-permissions): add secret manipulation

### PR DESCRIPTION
**Pull request by georgettica**
currently WIP as it was not tested on a cluster, will be tested later and will remove WIP
---

as we need to supply to the dedicated admin a way to modify the secrets in the 'openshift-logging' namespace

relevant role/rolebindings were created :)

### CODE REVIEW

**Comment by georgettica** [comment]
tested

**Review by NautiluX — COMMENTED** [review]
/lgtm

**Comment by NautiluX** [comment]
added hold for additional review, remove it once done.

**Comment by jewzaam** [comment]
This is re-inventing rbac for logging, only need to add secret to https://github.com/openshift/managed-cluster-config/blob/master/deploy/osd-logging/05-role.yaml 

/approve cancel
/lgtm cancel

**Comment by georgettica** [comment]
didn't see it, thank you for pointing it out!

**Pull request merged**
