### PR TITLE
Do not touch CMO config on management clusters

### PR DESCRIPTION
**Pull request by wanghaoran1988**
### What type of PR is this?
_(bug/feature/cleanup/documentation)_
bug

### What this PR does / why we need it?
We should not update the management clusters CMO config 
### Which Jira/Github issue(s) this PR fixes?

_Fixes #_ https://issues.redhat.com/browse/OSD-15675

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Comment by mrbarge** [comment]
The rework looks okay to me in terms of where it's going to land things.
A small request just for tidyness sake - could we rearrange all these under a common base directory?
ie.
`deploy/cluster-monitoring-config/` - contains the CMO config and config.yaml for normal, UWM-enabled clusters.
`deploy/cluster-monitoring-config/4.5/` - contains the CMO config and config.yaml for 4.5 clusters
`deploy/cluster-monitoring-config/non-uwm/` - contains the CMO config and config.yaml for non-uwm clusters

**Comment by jewzaam** [comment]
where is the JIRA for this work?

**Pull request closed without merging**
