### PR TITLE
SIGSRE-7: Forward ingress_canary_route_reachable metric

### PR DESCRIPTION
**Pull request by lisa**
Add `ingress_canary_route_reachable` to the list of forwarded metrics.

### CODE REVIEW

**Comment by lisa** [comment]
/hold

for review!

**Comment by dofinn** [comment]
Hi @lisa , please review https://github.com/openshift/ops-sop/blob/master/v4/howto/add-metrics-to-observatorium.md in regards to this :) your PR is close, but same MCC flow is used by updating https://github.com/openshift/managed-cluster-config/blob/1273d500a15bb7b7fd48001f05adf627edf38e24/deploy/cluster-monitoring-config/cluster-monitoring-config.yaml#L19 :+1:

**Pull request merged**
