### PR TITLE
Remove alert kubeAPILatencyHighSRE

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <yb532204897@gmail.com>

https://issues.redhat.com/browse/OSD-4441

This pr removes the `kubeAPILatencyHighSRE` alert, it is not needed anymore.

The upstream fix for `KubeAPILatency` is already backported to CMO https://github.com/openshift/cluster-monitoring-operator/pull/805.

Also this alert will be replaced with `KubeAPIErrorBudgetBurn` in OCP 4.6 https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/prometheus-k8s/rules.yaml#L1493.

### CODE REVIEW

**Comment by RiRa12621** [comment]
/hold
we need to wait a little more since the [upstream](https://bugzilla.redhat.com/show_bug.cgi?id=1845444) fix is not yet in a z-stream

**Comment by yeya24** [comment]
Is this [upstream](https://bugzilla.redhat.com/show_bug.cgi?id=1845444) already closed? When is the next z-release?

**Comment by RiRa12621** [comment]
Errata is out an it's going to be included in 4.4.14
So probably during the next rounds of upgrades we should have it

**Comment by NautiluX** [comment]
the new alert is available in 4.4.16 and upwards, so we can remove this one as far as I'm concerned.
/approve

**Review by NautiluX — APPROVED** [review]

**Comment by RiRa12621** [comment]
/unhold
can you rebase @yeya24 ?

**Comment by yeya24** [comment]
Sure!

**Comment by yeya24** [comment]
PTAL @RiRa12621 @NautiluX

**Pull request merged**
