### PR TITLE
[OSD-17129] Addition of self-managed ACS namespace prefix regex for cee backplane access

### PR DESCRIPTION
**Pull request by gjbravi**
### What type of PR is this?
feature

### What this PR does / why we need it?
The goal of this PR is to add the Self-managed ACS tenant's namespace prefix to the list of Red Hat owned namespaces in order to grant permission for read-only access for MCS support.

### Which Jira/Github issue(s) this PR fixes?
[OSD-17129](https://issues.redhat.com/browse/OSD-17129)

_Fixes #_

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Comment by Nanyte25** [comment]
@NautiluX whats holding this PR up from merging?

**Comment by Makdaam** [comment]
/lgtm
When the CI issue is resolved, please run retest.

**Pull request closed without merging**
