### PR TITLE
Use podman as a priority, fall back to docker

### PR DESCRIPTION
**Pull request by jharrington22**
Use podman as priority, fall back to docker.

Tested to generate files for #691

### CODE REVIEW

**Comment by dofinn** [comment]
are we standardizing on this across other makefiles in OSD?

**Comment by 2uasimojo** [comment]
> are we standardizing on this across other makefiles in OSD?

[Yes](https://github.com/openshift/boilerplate/blob/459c3cdf9d1bf451f99a08fbc21833c817d540e1/boilerplate/openshift/golang-osd-operator/standard.mk#L18-L19), but mcc is a snowflake and not likely to use boilerplate any time soon. (It's certainly not suited to the golang-osd-operator convention, which is the only one we have right now.)

**Comment by cblecker** [comment]
Based on this is what's in boilerplate, I'm fine with it.

/lgtm

**Comment by jharrington22** [comment]
Thanks

**Pull request merged**
