### PR TITLE
add configurable ignored namespace for MUO

### PR DESCRIPTION
**Pull request by bmeng**

### CODE REVIEW

**Comment by mrbarge** [comment]
/hold
/lgtm
Feel free to unhold when the corresponding MUO PR is merged.

**Comment by mrbarge** [comment]
/hold
as per above.

**Comment by bmeng** [comment]
cc @NautiluX 
Currently, there are multiple RMO related alerts which blocked the whole manged upgrade. We are going to ignore the RMO related alerts to make the upgrade going on as we assume the alerts there should not be blocker for the upgrade.
Please help check what is wrong for the RMO in e2e testing.

**Comment by mrbarge** [comment]
/hold
until 4.5 and 4.6 configmaps are also updated.

**Pull request merged**
