### PR TITLE
Adding ClusterRole level permissions for CSSRE

### PR DESCRIPTION
**Pull request by pat-cremin**
### What type of PR is this?
_(bug/feature/cleanup/documentation)_
feature
### What this PR does / why we need it?
Adding CllusterRole level access to RHOC clusters for CSSRE. 

### Which Jira/Github issue(s) this PR fixes?

_Fixes #_
[CSSRE-2260](https://issues.redhat.com//browse/CSSRE-2260)
### Pre-checks (if applicable):
- [x] Tested latest changes against a cluster
- [x] Included documentation changes with PR
- [x] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Comment by pat-cremin** [comment]
needs `make` run @jessesarn

**Comment by pat-cremin** [comment]
needs `make` run @jessesarn

**Review by jewzaam — CHANGES_REQUESTED** [review]
run `make` please

**Pull request merged**
