### PR TITLE
add configmap for sts policies

### PR DESCRIPTION
**Pull request by pvasant**
cc: @vkareh 

The idea is to have these policies available in a ConfigMap in the hive/provisioning cluster so that OCM can read from it and prompt the user to create those policies in their cloud
 
https://issues.redhat.com/browse/SDA-4890

### CODE REVIEW

**Comment by vkareh** [comment]
There is a SelectorSyncSet that probably shouldn't be there.

I wonder if the MCC repo allows for a Makefile that compiles the final YAML file. This way we can pull the policies straight from the `resources/sts/` dir and be always in sync.

/cc @jharrington22

**Comment by pvasant** [comment]
> There is a SelectorSyncSet that probably shouldn't be there.
> 
> I wonder if the MCC repo allows for a Makefile that compiles the final YAML file. This way we can pull the policies straight from the `resources/sts/` dir and be always in sync.
> 
> /cc @jharrington22

I did read about the make file in ReadMe but wanted a head start so we can discuss

**Comment by wanghaoran1988** [comment]
Is there a jira tracking this? shouldn't the policy created during the installation phase, how we gonna consume this configmap?

**Comment by fahlmant** [comment]
@pvasant @vkareh We already have these defined here https://github.com/openshift/managed-cluster-config/tree/master/resources/sts/4.9

**Review by fahlmant — CHANGES_REQUESTED** [review]
@pvasant @vkareh We already have these defined here https://github.com/openshift/managed-cluster-config/tree/master/resources/sts/4.9

Why are they needing to be added to hive?

**Comment by vkareh** [comment]
@fahlmant 
> Why are they needing to be added to hive?

OCM needs access to these so that we can create roles/policies on behalf of the user on their cloud account. Also, the ROSA CLI needs to have these served from the OCM API to guide the user through the process of creating them. The idea is to decouple these policies from binary releases of the CLI.

**Comment by fahlmant** [comment]
Any reason not to just grab them from github though?

**Comment by pvasant** [comment]
@fahlmant  we need it in two places both in ocm and ROSA so instead of copying the files in both places, we need a single source of truth.

**Comment by fahlmant** [comment]
This is meant to be the source of truth https://github.com/openshift/managed-cluster-config/tree/master/resources/sts/4.9

**Comment by pvasant** [comment]
The idea is 
1) We need to decouple the policy from rosa cli so we don't want to release rosa every time policy changes 
it is right now in   https://github.com/openshift/rosa/tree/master/templates/policies 

2) We also need to use these policies in OCM API to enable users to create the roles and policies on behalf of them

**Comment by vkareh** [comment]
> This is meant to be the source of truth https://github.com/openshift/managed-cluster-config/tree/master/resources/sts/4.9

@pvasant - this is a good point. Maybe we should just use the GitHub API to fetch these files in OCM (which I think you suggested initially). I don't like this, to be honest, as then OCM is bound to the file structure of MCC, which is why I suggested instead pushing these files to a ConfigMap that OCM can read.

**Comment by fahlmant** [comment]
Currently we don't have a makefile for anything in `resources`. Feel free to add one. As long as the config is drawing from there we can move forward; that way any changes to the source of truth files will automatically be reflected in the config

**Comment by pvasant** [comment]
@cblecker @jharrington22  Can you please help with this one. Using GitHub API has its own limitation of rate-limiting etc and it is not scalable though we could restrict it to run every day. But if we can get this as a config map it will be really helpful. 
@fahlmant  can you give an example of the make file  cc: @vkareh

**Comment by maorfr** [comment]
as discussed on the OSD sync call, this is more fitting for being deployed through app-interface.
more information in https://issues.redhat.com/browse/OSD-9896

**Comment by maorfr** [comment]
internal discussion going on in https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/33572

**Comment by maorfr** [comment]
replaced by https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/33598

**Pull request closed without merging**
