### PR TITLE
Add SSS to patch candidate and fast channels in ClusterVersion

### PR DESCRIPTION
**Pull request by jewzaam**
https://issues.redhat.com/browse/OSD-6205

### CODE REVIEW

**Comment by jewzaam** [comment]
/hold

we have some stuff being promoted, just holding to make sure I don't muddy the promotion with this

**Comment by dofinn** [comment]
I thought only candidate channels were impacted by this ?

**Comment by mrbarge** [comment]
> I thought only candidate channels were impacted by this ?

It happens on clusters installing a `fast` version too, unfortunately. It's the OCP installer doing it, it just defaults clusters to be on `stable` post-install.

The change looks fine to me. I'm a little worried that we have both an SSS and MUO trying to update that field using a different part of CS as their source of truth (MUO uses `upgrade_channel_group`, SSS uses the `clusterdeployment` label).. although I've been wracking my brain to think of potential ways it could break and can't think of any scenarios. MUO only sets the field at upgrade time, and at that point in time the clusterdeployment's label should already have a matching value to that in CS's `upgrade_channel_group`.

**Comment by jewzaam** [comment]
@mrbarge same re: two sources to set it.  I tried to lay out my thoughts in the readme.  I'll update with specific scenarios since I still do fear there is something overlooked :)

**Review by NautiluX — COMMENTED** [review]
/lgtm

**Comment by jewzaam** [comment]
/hold cancel

Removed hold since I plan to test shortly after it lands.  And there isn't any pending promotion this could hold up.

**Pull request merged**
