### PR TITLE
OSD-6703: adding RMO metrics to observatorium

### PR DESCRIPTION
**Pull request by ramonbutter**
With the following [proposal](https://gitlab.cee.redhat.com/rbutter/lifecycler/-/blob/eacd7f0509e67794848b933d416a12661f481751/lifecycles/observatorium/probe_success.md)

### CODE REVIEW

**Comment by ramonbutter** [comment]
@sre-observatorium

**Comment by dofinn** [comment]
cc @sre-observatorium

**Comment by dofinn** [comment]
All looks fine to me, including the proposal, would like others to review. When ready `/unhold` for merging.

**Comment by dofinn** [comment]
cc @openshift/team-sre-mst-observatorium

**Comment by dofinn** [comment]
Hi @ramonbutter  was there also a metric proposal for the addtional `probe_duration_in_seconds` metric anywhere?

**Comment by ramonbutter** [comment]
@dofinn sorry for the delay. I have at the moment problems accessing GitLab. I will ping team-sre-observatorium once it is fully done

**Comment by ramonbutter** [comment]
@openshift/team-sre-mst-observatorium I created a MR to lifecycler including both proposals

**Pull request merged**
