### PR TITLE
Revert "Updated logic for MCC"

### PR DESCRIPTION
**Pull request by lnguyen1401**
This reverts commit db23d22104621a024fcc9415644ff9d9c658d77a.

### What type of PR is this?
_(bug/feature/cleanup/documentation)_
bug
### What this PR does / why we need it?
Reverted the refactor, since the generated files have root permission by default and CI can't clean up after running PR check 
https://redhat-internal.slack.com/archives/CFJD1NZFT/p1688551491525979?thread_ts=1688449690.735299&cid=CFJD1NZFT

### Which Jira/Github issue(s) this PR fixes?

_Fixes #_

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Review by rafael-azevedo — APPROVED** [review]
/lgtm

**Review by fahlmant — APPROVED** [review]
/approve

**Pull request merged**
