### PR TITLE
FedRAMP Suricata SCC Fixes

### PR DESCRIPTION
**Pull request by dustman9000**
Fixup FedRAMP Suricata SCC implementation and remove privileged container usage.

### What type of PR is this?
_cleanup_

### Which Jira/Github issue(s) this PR fixes?

_Fixes [OSD-17781](https://issues.redhat.com/browse/OSD-17781)_

### CODE REVIEW

**Comment by dustman9000** [comment]
/hold cancel
Tested successfully on a FedRAMP ROSA cluster.

**Review by mjlshen — APPROVED** [review]
/lgtm

**Review by rhdedgar — APPROVED** [review]
Looks good as discussed, thank you for the contribution!

**Pull request merged**
