### PR TITLE
Use StringLike condition to match wildcard

### PR DESCRIPTION
**Pull request by jharrington22**
### What type of PR is this?
bug

### What this PR does / why we need it?
Use `StringLike` condition to match wildcard value in `Via:Service` context key.

### Which Jira/Github issue(s) this PR fixes?

```
aws accessanalyzer validate-policy --policy-type IDENTITY_POLICY --policy-document file://openshift_hcp_capa_controller_manager_credentials_policy.json/ --region us-east-1
{
    "findings": [
        {
            "findingDetails": "Your condition value includes a * or ? character. If you meant to use a wildcard (*, ?), update the condition operator to include Like.",
            "findingType": "WARNING",
            "issueCode": "WILDCARD_WITHOUT_LIKE_OPERATOR",
            "learnMoreLink": "https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-reference-policy-checks.html#access-analyzer-reference-policy-checks-general-warning-wildcard-without-like-operator",
            "locations": [
                {
                    "path": [
                        {
                            "value": "Statement"
                        },
                        {
                            "index": 14
                        },
                        {
                            "value": "Condition"
                        },
                        {
                            "value": "StringEquals"
                        },
                        {
                            "value": "kms:ViaService"
                        }
                    ],
                    "span": {
                        "start": {
                            "line": 233,
                            "column": 28,
                            "offset": 5315
                        },
                        "end": {
                            "line": 233,
                            "column": 49,
                            "offset": 5336
                        }
                    }
                }
            ]
        }
    ]
}
```

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Comment by jharrington22** [comment]
@fahlmant cluster is ready and machinepool is good. 

```
rosa list machinepools -c jh-kms --region us-east-1
ID       AUTOSCALING  DESIRED REPLICAS  CURRENT REPLICAS  INSTANCE TYPE  LABELS    TAINTS    AVAILABILITY ZONE  SUBNET                    VERSION  AUTOREPAIR  MESSAGE  
workers  No           3                 3                 m5.xlarge                          us-west-2a         subnet-005a2d98f03506c2e  4.12.12  Yes
```

**Review by fahlmant — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
