### PR TITLE
Fix ROSA logo `alt`

### PR DESCRIPTION
**Pull request by wgordon17**
### What type of PR is this?
_(bug/feature/cleanup/documentation)_

### Which Jira/Github issue(s) this PR fixes?

_Fixes #_

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR
- [ ] If this is a new object that is not intended for the FedRAMP environment (if unsure, please reach out to team FedRAMP), please exclude it with:

    ```yaml
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    ```

### CODE REVIEW

**Review by jewzaam — CHANGES_REQUESTED** [review]
run `make` to generate updated secrets and templates for deployment

**Comment by wgordon17** [comment]
@jewzaam `make` files included 👍

**Pull request merged**
