### PR TITLE
Added persistent storage for the monitoring stack

### PR DESCRIPTION
**Pull request by dak1n1**
Add persistent volumes to Prometheus and Alertmanager pods. SREP-1171

### CODE REVIEW

**Comment by jeremyeder** [comment]
@brancz @sichvoge I anticipate needing to justify why this isn't the default for  the OCP product.  Can you please comment here the succinct reasoning, so we have it for future reference?

**Comment by brancz** [comment]
We have no default storage class we can use for bare metal installs, plus volume resizing isn’t a thing yet. Hence customers need to do capacity planning for storage, which they can more safely and easily do with an emptyDir to start out with.

**Comment by sichvoge** [comment]
@brancz is that something that will change as soon as local volume is generally available on OpenShift?

**Comment by brancz** [comment]
Even with local volumes being generally available, a local volume needs to exist, which is not guaranteed.

**Comment by jeremyeder** [comment]
In stage yesterday:

```$ oc get ev -n openshift-monitoring 
LAST SEEN   TYPE      REASON         OBJECT                          MESSAGE
14s         Warning   FailedCreate   statefulset/alertmanager-main   create Claim alertmanager-data-alertmanager-main-0 for Pod alertmanager-main-0 in StatefulSet alertmanager-main failed er
ror: persistentvolumeclaims "alertmanager-data-alertmanager-main-0" is forbidden: exceeded quota: persistent-volume-quota, requested: requests.storage=10Gi, used: requests.storage=0, limited: requests.storage=100
5m14s       Warning   FailedCreate   statefulset/alertmanager-main   create Pod alertmanager-main-0 in StatefulSet alertmanager-main failed error: Failed to create PVC alertmanager-data-aler
tmanager-main-0: persistentvolumeclaims "alertmanager-data-alertmanager-main-0" is forbidden: exceeded quota: persistent-volume-quota, requested: requests.storage=10Gi, used: requests.storage=0, limited: requests.storage=100
14s         Warning   FailedCreate   statefulset/prometheus-k8s      create Claim prometheus-data-prometheus-k8s-0 for Pod prometheus-k8s-0 in StatefulSet prometheus-k8s failed error: persis
tentvolumeclaims "prometheus-data-prometheus-k8s-0" is forbidden: exceeded quota: persistent-volume-quota, requested: requests.storage=50Gi, used: requests.storage=0, limited: requests.stora
ge=100
85m         Warning   FailedCreate   statefulset/prometheus-k8s      create Pod prometheus-k8s-0 in StatefulSet prometheus-k8s failed error: Failed to create PVC prometheus-data-prometheus-k8s-0: persistentvolumeclaims "prometheus-data-prometheus-k8s-0" is forbidden: exceeded quota: persistent-volume-quota, requested: requests.storage=50Gi, used: requests.storage=0, limited: requests.storage=100
```

This is causing a failing test in our e2e:
https://prow.k8s.io/view/gcs/redhat-openshift-osd-e2e/logs/osd-stage-4.1/139

**Comment by dak1n1** [comment]
@jeremyeder There are some related changes[1][2] that didn't get merged into stage or prod yesterday. I'll follow up on those and see if I can solve this issue today.

[1] https://github.com/openshift/managed-cluster-config/pull/28
[2] https://github.com/openshift/managed-cluster-config/pull/27

**Comment by dak1n1** [comment]
Naveen is working on the fix here: https://github.com/openshift/managed-cluster-config/pull/32 It was caused by another PR that was merged without running `make`. So he added a check to prevent this in the future.

**Pull request merged**
